apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: sandbox
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 8080
  type: NodePort